/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and set a session cookie.
         *
         *     Verifies the supplied credentials against the stored scrypt hash.  On
         *     success, creates a JWT session token and sets it as an HttpOnly,
         *     SameSite=Strict cookie and clears the client's failure window.  On failure,
         *     records the attempt and returns 401 — after too many recent failures the
         *     client is locked out with 429 (non-blocking, no ``time.sleep``).
         *
         *     Args:
         *         body: The login credentials (username + password).
         *         request: The incoming FastAPI request (for app.state access).
         *
         *     Returns:
         *         A ``Response`` with status 204 and a ``Set-Cookie`` header on success.
         *
         *     Raises:
         *         HTTPException: 429 once the client exceeds the failed-attempt threshold;
         *             401 if the credentials are invalid or the server is not fully
         *             configured (missing password hash or JWT secret).
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie (log out).
         *
         *     Requires a valid session (guarded by ``require_session``).
         *
         *     Args:
         *         session: The authenticated session injected by the guard.
         *
         *     Returns:
         *         A ``Response`` with status 204 and a cookie-clearing ``Set-Cookie`` header.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's identity.
         *
         *     Requires a valid session (guarded by ``require_session``).
         *
         *     Args:
         *         session: The authenticated session injected by the guard.
         *
         *     Returns:
         *         A dict with the ``username`` key.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files
         * @description Return metadata for every file in the config overlays array.
         *
         *     Lists the master config.json5, each declared overlay, and local.json5
         *     (if present).  For each file computes the SHA-256 digest, filesystem
         *     stat info, and shadowed keys (keys overridden by local.json5).
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`FilesResponse` with one :class:`FileInfo` per file.
         */
        get: operations["get_files_api_config_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Return the parsed contents of a single config file.
         *
         *     Args:
         *         name: Config file basename (e.g. ``"paths.json5"``).
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`FileContent` with parsed values, SHA-256, and shadowed keys.
         *
         *     Raises:
         *         404: If *name* is not a declared overlay, ``local.json5``, or
         *             ``config.json5``.
         */
        get: operations["get_file_api_config_files__name__get"];
        /**
         * Put File
         * @description Validate and atomically write a config overlay file.
         *
         *     Order:
         *     1. Role check — 403 if staging (read-only).
         *     2. Existence check — 404 if *name* is not a writable file
         *        (overlays + local.json5; master is read-only through this endpoint).
         *     3. SHA-256 precondition — 412 if *body.base_sha256* ≠ current
         *        on-disk digest (empty string for a non-existent local.json5).
         *     4. Validate candidate via
         *        :func:`~personalscraper.conf.loader.validate_candidate` — 422
         *        with Pydantic error loc paths on failure (no backup created).
         *     5. Backup current file to ``.backups/{name}.{utc}.json5``, prune to
         *        10 most recent per file name.
         *     6. Atomic write via temp file + ``os.replace`` + ``fsync``,
         *        serialized with a module-level ``threading.Lock``.
         *     7. Return 200 with warnings and restart-required flag.
         *
         *     Args:
         *         name: Config file basename (e.g. ``"paths.json5"``).
         *         body: Request payload with ``values`` and ``base_sha256``.
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`PutFileResponse` with warnings and restart_required flag.
         *
         *     Raises:
         *         403: If ``PERSONALSCRAPER_WEB_ROLE`` is ``"staging"``.
         *         404: If *name* is not a writable config file.
         *         409: If *name* is valid but another declared overlay is missing on
         *             disk (``ConfigLoadError``).
         *         412: If *body.base_sha256* does not match the current on-disk file
         *             digest.
         *         422: If the candidate values fail Pydantic validation, or if the
         *             candidate introduces a key owned by another overlay
         *             (``ConfigConflictError``).
         */
        put: operations["put_file_api_config_files__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/restart-web": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Web
         * @description Schedule a PM2 restart of the web process.
         *
         *     The restart is handed off to a detached subprocess that sleeps 0.5 s
         *     (so the 202 response flushes first), then runs ``pm2 restart`` on the
         *     name configured in ``PERSONALSCRAPER_PM2_NAME``.  The subprocess stdout
         *     and stderr are redirected to a log file under the system temp directory
         *     (``<tempdir>/torrentmate-restart-web.log``, truncated per spawn) so a
         *     failed pm2 invocation leaves a trace.
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         202 with :class:`RestartResponse` ``{"status": "scheduled"}``.
         *
         *     Raises:
         *         403: If ``PERSONALSCRAPER_WEB_ROLE`` is ``"staging"``.
         *         404: If ``PERSONALSCRAPER_PM2_NAME`` is not set in the environment.
         */
        post: operations["restart_web_api_config_restart_web_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Return the JSON Schema, key ownership, and restart-impact map.
         *
         *     Computes the JSON Schema from ``Config.model_json_schema()``, derives
         *     key ownership from the overlays array in master config.json5, and
         *     returns the static RESTART_IMPACT map.
         *
         *     The result is cached on ``request.app.state`` (lazy, first access).
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`ConfigSchemaResponse` with schema, ownership, and restart
         *         impact data.
         */
        get: operations["get_schema_api_config_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Secrets
         * @description Return the secret key catalog with ``is_set`` flags.
         *
         *     Parses ``.env.example`` at the project root to enumerate known keys
         *     and their descriptions, then checks ``.env`` for which keys currently
         *     have a non-empty value.  Secret values are **never** included in the
         *     response.
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`SecretsResponse` with one :class:`SecretEntry` per key.
         */
        get: operations["get_secrets_api_config_secrets_get"];
        /**
         * Put Secrets
         * @description Write secret values to ``.env`` via atomic upsert.
         *
         *     Only keys declared in ``.env.example`` are accepted.  Secret values are
         *     **never** logged.
         *
         *     Args:
         *         body: Mapping of ``{KEY: value, ...}`` to upsert into ``.env``.
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`PutFileResponse` with ``restart_required=True``.
         *
         *     Raises:
         *         403: If ``PERSONALSCRAPER_WEB_ROLE`` is ``"staging"``.
         *         422: If any key in *body* is not in the catalog.  Values are
         *             **never** echoed in the error detail.
         */
        put: operations["put_secrets_api_config_secrets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Return deployment status: role, read-only flag, and stale file detection.
         *
         *     Compares current on-disk SHA-256 digests against the boot-time snapshot
         *     (captured lazily on first access).  A file is *stale* when its current
         *     digest differs from boot time.  *restart_required* is ``True`` when any
         *     stale file exists.
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`ConfigStatusResponse` with role, read_only, restart_required,
         *         and stale_files.
         */
        get: operations["get_status_api_config_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate File
         * @description Validate a candidate config file without writing to disk.
         *
         *     Calls :func:`~personalscraper.conf.loader.validate_candidate` with a
         *     single-file replacement.  On success returns warnings; on failure
         *     returns 422 with Pydantic error loc paths.
         *
         *     Args:
         *         body: The validation request with ``file_name`` and ``values``.
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A :class:`ValidateResponse` with any warnings from the validator.
         *
         *     Raises:
         *         404: If *body.file_name* is not a known overlay or ``local.json5``.
         *         422: If the candidate values fail Pydantic validation, with detail
         *             carrying the error loc paths extracted from the underlying
         *             :class:`pydantic.ValidationError`.
         */
        post: operations["validate_file_api_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health-check endpoint — reachable, Redis, and DB presence.
         *
         *     Both probes are **fail-soft**: they never raise and never block boot.
         *     A down Redis or missing DB returns ``false`` for that key, not a 5xx.
         *
         *     Returns:
         *         A dict with:
         *         - **status**: Always ``"ok"`` if this handler is reachable.
         *         - **redis**: ``True`` if the configured Redis instance responds to PING.
         *         - **db**: ``True`` if ``library.db`` exists at the configured data_dir path.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actions
         * @description Return the full maintenance action registry with category counts.
         *
         *     The registry is defined at module level in
         *     :mod:`personalscraper.web.maintenance.registry` and is read-only at
         *     runtime — no database or filesystem access is needed.
         *
         *     Returns:
         *         An :class:`ActionsResponse` with all 25 registered actions and
         *         per-category counts for UI grouping chips.
         */
        get: operations["get_actions_api_maintenance_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/actions/{action_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Run
         * @description Launch a maintenance action as a detached subprocess.
         *
         *     Mirror of ``POST /api/pipeline/run`` — validates the action id, options, and
         *     preconditions (pipeline lock, concurrent maintenance run, dry-run-first for
         *     destructive actions), then spawns a runner subprocess and returns ``202``
         *     with the ``run_uid``.
         *
         *     Args:
         *         action_id: The kebab-case action id (e.g. ``"library-index"``).
         *         body: The request payload with ``options`` and ``dry_run``.
         *         request: The incoming FastAPI request (for ``app.state`` access).
         *
         *     Returns:
         *         ``202`` with :class:`ActionRunResponse` (``{"run_uid": "..."}``).
         *
         *     Raises:
         *         404: *action_id* is not in the :data:`REGISTRY`.
         *         422: Invalid or missing options, or dry-run requested for an action
         *             that does not support it.
         *         409: The pipeline lock is held, or a maintenance action is already running.
         *         428: A destructive action was requested without a recent successful
         *             dry run (same options, within the last 30 minutes).
         */
        post: operations["action_run_api_maintenance_actions__action_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/disks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Disks
         * @description Return mount status and capacity for every configured storage disk.
         *
         *     Iterates ``config.disks``, calling :func:`get_disk_status` for each.
         *     Total capacity is derived from ``shutil.disk_usage`` at query time
         *     (DiskConfig does not carry a ``size_gb`` field).
         *
         *     Returns:
         *         A :class:`DisksResponse` with one entry per configured disk.
         */
        get: operations["get_disks_api_maintenance_disks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/index-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Index Health
         * @description Return an aggregate health snapshot of the indexer database.
         *
         *     Opens a regular connection to ``library.db`` (mirroring the pipeline
         *     history route) and runs a single batch of lightweight aggregate
         *     queries.  No filesystem walk is performed.  When the database file is
         *     missing or unreadable, a zeroed response is returned (fail-soft, no
         *     500).
         *
         *     Query summary:
         *
         *     * ``media_item`` total + movie/show breakdown (``kind`` column).
         *     * ``media_file`` count + ``size_bytes`` sum (non-deleted only).
         *     * NFO status breakdown (``valid`` / ``invalid`` / ``missing``).
         *     * ``repair_queue`` pending count + oldest ``enqueued_at`` age.
         *     * ``index_outbox`` pending count + oldest ``created_at`` age
         *       (table-missing → 0 / ``None``, fail-soft).
         *     * ``scan_run`` latest row with stuck detection (> 1 h running).
         *     * Soft-deleted ``media_file`` rows (``deleted_at IS NOT NULL``).
         *     * ``media_item`` rows with ``canonical_provider IS NULL``.
         *
         *     Returns:
         *         A :class:`IndexHealthResponse` with per-table counts, NFO stats,
         *         queue backlogs, and the most recent scan run metadata.
         */
        get: operations["get_index_health_api_maintenance_index_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Locks
         * @description Return pipeline lock state, sentinels, and bounded tmp-orphan sweep.
         *
         *     Reads ``pipeline.lock``, ``pipeline.pause``, and ``watcher.paused``
         *     from the configured ``data_dir``, then performs a bounded filesystem
         *     sweep for stale ``_tmp_dispatch_*`` / ``_tmp_ingest_*`` entries
         *     across staging and disk roots (capped at 100 entries, depth ≤ 2).
         *
         *     Returns:
         *         A :class:`LocksResponse` with lock, sentinel, and orphan data.
         */
        get: operations["get_locks_api_maintenance_locks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline History
         * @description Return paginated pipeline run history.
         *
         *     Opens a fresh read-only connection to the indexer database on every
         *     request.  The database uses WAL mode so concurrent reads are safe.
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *         limit: Maximum number of runs to return (default 50).
         *         offset: Number of runs to skip (default 0).
         *         sort: Sort order — one of ``started_at``, ``-started_at``,
         *             ``duration``, ``-duration`` (default ``-started_at``).
         *         kind: Run kind filter — one of ``"pipeline"``, ``"maintenance"``,
         *             or ``"all"`` (default ``"all"``).
         *
         *     Returns:
         *         A ``HistoryResponse`` with the requested page of run summaries.
         *         ``total`` reflects the filtered count, not the full table.
         *
         *     Raises:
         *         HTTPException: 400 if *sort* or *kind* is not one of the
         *             allowed values.
         */
        get: operations["pipeline_history_api_pipeline_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/history/{run_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline History Detail
         * @description Return the full detail for a single pipeline run.
         *
         *     Parses the ``steps_json`` column into per-step timing records.
         *
         *     Args:
         *         run_uid: The unique run identifier.
         *         request: The incoming FastAPI request.
         *
         *     Returns:
         *         A ``RunDetail`` with step timings parsed from ``steps_json``.
         *
         *     Raises:
         *         HTTPException: 404 if no run with the given *run_uid* exists; 500 if the
         *             database read fails (un-migrated / locked DB) — a genuine operational
         *             error must not masquerade as "run not found".
         */
        get: operations["pipeline_history_detail_api_pipeline_history__run_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline Kill
         * @description Kill the running pipeline subprocess with SIGTERM.
         *
         *     Reads the PID from ``pipeline.lock``, sends ``SIGTERM``, and clears
         *     the pause sentinel.  The run process releases the lock and finalizes
         *     its history row as ``killed`` on its way out.
         *
         *     Returns the current pipeline status (fail-soft: if the lock is absent
         *     or unreadable, returns the idle status without error).
         */
        post: operations["pipeline_kill_api_pipeline_kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline Pause
         * @description Create the ``pipeline.pause`` sentinel to pause the running pipeline.
         *
         *     No-op if no pipeline is currently running (the sentinel is still
         *     created — it will be honoured on the next run, which is harmless since
         *     a fresh run clears it).
         *
         *     Returns the current pipeline status.
         */
        post: operations["pipeline_pause_api_pipeline_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline Resume
         * @description Remove the ``pipeline.pause`` sentinel to resume a paused pipeline.
         *
         *     Returns the current pipeline status.
         */
        post: operations["pipeline_resume_api_pipeline_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline Run
         * @description Launch a new pipeline run as a detached subprocess.
         *
         *     Returns ``202 {run_uid}`` on success, or ``409`` if the pipeline lock
         *     is already held by another process.
         */
        post: operations["pipeline_run_api_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline Status
         * @description Return the live pipeline status.
         *
         *     Reads the lock, pause sentinel, watcher sentinel, and the latest
         *     ``pipeline_run`` database row to compose a full status snapshot.
         *     This is the only route in the group that does **not** require the
         *     ``X-Requested-With`` header (it is a read-only GET).
         *
         *     Returns:
         *         A ``StatusResponse`` with the current pipeline state and metadata.
         */
        get: operations["pipeline_status_api_pipeline_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/watcher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline Watcher
         * @description Enable or pause the directory watcher daemon.
         *
         *     When *enabled* is ``True`` the ``watcher.paused`` sentinel is removed
         *     (watcher runs).  When ``False`` the sentinel is created (watcher pauses).
         *     This is independent of the pipeline run itself — pausing the watcher
         *     only prevents the daemon from auto-starting new runs.
         *
         *     Args:
         *         request: The incoming FastAPI request.
         *         body: The watcher toggle payload with ``enabled: bool``.
         *
         *     Returns:
         *         The watcher state reflecting the requested change.
         */
        post: operations["pipeline_watcher_api_pipeline_watcher_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Application version endpoint.
         *
         *     Returns:
         *         A dict with ``version`` (the Python package version) and
         *         ``build_commit`` (the deployed git SHA, or ``"dev"``).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionOption
         * @description A single targeting option for a maintenance action.
         *
         *     Models one CLI flag or positional argument. The ``type`` field drives
         *     the form control rendered in the web UI (text input, number input,
         *     checkbox, or dropdown). Enum values are the valid choices for a
         *     ``select`` / dropdown control.
         *
         *     Attributes:
         *         name: CLI-facing name (flag name without leading dashes, or
         *             positional arg name). Used as the JSON key in ``options_json``.
         *         type: Form-control type — ``"str"`` for text, ``"int"`` for number,
         *             ``"bool"`` for checkbox, ``"enum"`` for dropdown.
         *         enum_values: Valid choices when ``type="enum"``. ``None`` otherwise.
         *         default: Default value matching the CLI default. ``None`` when the
         *             CLI has no default (optional flags) or when the value is a
         *             required positional.
         *         required: ``True`` for mandatory positional arguments (e.g.
         *             ``library-search``'s ``query``). ``False`` for optional flags.
         *         label: French label for the web UI form field.
         *         help: French help text / placeholder for the web UI form field.
         */
        ActionOption: {
            /** Default */
            default?: string | number | boolean | null;
            /** Enum Values */
            enum_values?: string[] | null;
            /** Help */
            help: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Type
             * @enum {string}
             */
            type: "str" | "int" | "bool" | "enum";
        };
        /**
         * ActionRunRequest
         * @description Request body for ``POST /api/maintenance/actions/{action_id}/run``.
         *
         *     Mirrors the S2 :class:`~personalscraper.web.models.pipeline.RunRequest`
         *     pattern: a flat payload with optional options and a safety-default
         *     ``dry_run``.
         *
         *     Attributes:
         *         options: Key-value pairs of CLI flags or arguments for the
         *             maintenance action.  Each key is validated against the
         *             action's registered :class:`ActionOption` entries in the
         *             :data:`REGISTRY`.  Defaults to an empty dict.
         *         dry_run: When ``True`` (the default), the action performs a dry
         *             run without mutating the filesystem or database.  Only
         *             meaningful when the action's ``dry_run`` capability is
         *             ``"supported"``.
         */
        ActionRunRequest: {
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /**
             * Options
             * @default {}
             */
            options: {
                [key: string]: unknown;
            };
        };
        /**
         * ActionsResponse
         * @description Top-level response for the maintenance actions catalog.
         *
         *     Serves the ``GET /api/maintenance/actions`` endpoint. Returns the full
         *     read-only :data:`REGISTRY` (25 entries across 6 categories) together
         *     with per-category counts for the web UI grouping chips.
         *
         *     Attributes:
         *         actions: The full maintenance action registry (25 entries across
         *             the query, scan, repair, clean, analyze, and fix categories).
         *         category_counts: Count of actions per category for UI grouping chips
         *             (e.g. ``{"query": 5, "scan": 4, "repair": 2, "clean": 2,
         *             "analyze": 4, "fix": 8}``).
         */
        ActionsResponse: {
            /** Actions */
            actions: components["schemas"]["MaintenanceAction"][];
            /** Category Counts */
            category_counts: {
                [key: string]: number;
            };
        };
        /**
         * ConfigSchemaResponse
         * @description Response body for ``GET /api/config/schema``.
         *
         *     Attributes:
         *         json_schema: JSON Schema for the merged config (generated via
         *             ``Config.model_json_schema()``).
         *         ownership: Mapping of each top-level key to the file that owns it.
         *         restart_impact: Mapping of each top-level key to whether changing
         *             it requires a web process restart.
         */
        ConfigSchemaResponse: {
            /** Json Schema */
            json_schema: {
                [key: string]: unknown;
            };
            /** Ownership */
            ownership: {
                [key: string]: string;
            };
            /** Restart Impact */
            restart_impact: {
                [key: string]: boolean;
            };
        };
        /**
         * ConfigStatusResponse
         * @description Response body for ``GET /api/config/status``.
         *
         *     Attributes:
         *         role: Deployment role (``"prod"`` or ``"staging"``).
         *         read_only: Whether the web process is in read-only mode.
         *         restart_required: Whether ``stale_files`` is non-empty.
         *         restart_configured: Whether ``PERSONALSCRAPER_PM2_NAME`` is set in the
         *             environment (controls visibility of the restart button in the UI).
         *         stale_files: Config filenames whose on-disk SHA-256 differs from the
         *             boot-time snapshot.
         */
        ConfigStatusResponse: {
            /** Read Only */
            read_only: boolean;
            /** Restart Configured */
            restart_configured: boolean;
            /** Restart Required */
            restart_required: boolean;
            /** Role */
            role: string;
            /** Stale Files */
            stale_files: string[];
        };
        /**
         * DiskInfo
         * @description A single configured storage disk with its mount and capacity data.
         *
         *     Attributes:
         *         id: The disk identifier as declared in ``config/disks.json5``
         *             (e.g. ``"disk_1"``, ``"disk_2"``).
         *         label: Human-readable disk label configured by the operator.
         *         mounted: ``True`` if the disk mount path currently exists and is
         *             accessible on the filesystem.
         *         free_gb: Free space in gibibytes, rounded to one decimal.
         *         total_gb: Total capacity in gibibytes, derived from
         *             ``shutil.disk_usage(path).total`` at query time.
         *         used_pct: Percentage of capacity currently in use, rounded to one
         *             decimal (``(1 - free_gb / total_gb) * 100``).
         */
        DiskInfo: {
            /** Free Gb */
            free_gb: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Mounted */
            mounted: boolean;
            /** Total Gb */
            total_gb: number;
            /** Used Pct */
            used_pct: number;
        };
        /**
         * DisksResponse
         * @description Top-level response for the disks monitoring panel.
         *
         *     Attributes:
         *         disks: List of disk info entries, one per configured disk.
         */
        DisksResponse: {
            /** Disks */
            disks: components["schemas"]["DiskInfo"][];
        };
        /**
         * FileContent
         * @description Response body for ``GET /api/config/files/{name}``.
         *
         *     Attributes:
         *         name: Config file basename.
         *         values: Parsed JSON5 contents keyed by top-level key.
         *         sha256: Hex digest of the file contents on disk.
         *         shadowed_keys: Keys in this file overridden by ``local.json5``.
         */
        FileContent: {
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
            /** Shadowed Keys */
            shadowed_keys: string[];
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * FileInfo
         * @description Metadata for a single config file listed in ``GET /api/config/files``.
         *
         *     Attributes:
         *         name: Config file basename (e.g. ``"master.json5"``).
         *         owned_keys: Top-level keys owned by this file.
         *         sha256: Hex digest of the file contents on disk.
         *         mtime: Last modification time as a Unix timestamp (float).
         *         size: File size in bytes.
         *         shadowed_keys: Keys owned by this file that are overridden by
         *             ``local.json5``.
         */
        FileInfo: {
            /** Mtime */
            mtime: number;
            /** Name */
            name: string;
            /** Owned Keys */
            owned_keys: string[];
            /** Sha256 */
            sha256: string;
            /** Shadowed Keys */
            shadowed_keys: string[];
            /** Size */
            size: number;
        };
        /**
         * FilesResponse
         * @description Response body for ``GET /api/config/files``.
         *
         *     Attributes:
         *         files: Metadata for every file in the config overlays array.
         */
        FilesResponse: {
            /** Files */
            files: components["schemas"]["FileInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health-check endpoint.
         *
         *     Attributes:
         *         status: Always ``"ok"`` if the handler is reachable.
         *         redis: ``True`` if the configured Redis instance responds to PING.
         *         db: ``True`` if ``library.db`` exists at the configured data_dir path.
         */
        HealthResponse: {
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
            /** Status */
            status: string;
        };
        /**
         * HistoryResponse
         * @description Paginated response for the run-history list endpoint.
         *
         *     Attributes:
         *         runs: List of run summaries for the current page.
         *         total: Total number of runs in the database (for pagination).
         */
        HistoryResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
        };
        /**
         * IndexHealthResponse
         * @description Aggregate health snapshot of the indexer database (``library.db``).
         *
         *     All fields are derived from a single read-only WAL query over the
         *     database; no filesystem walk is performed.
         *
         *     Attributes:
         *         items: Total number of rows in ``media_item``.
         *         movies: Number of media items with a movie category.
         *         shows: Number of media items with a TV-show category.
         *         files: Total number of rows in ``media_file``.
         *         size_gb: Sum of ``media_file.size_bytes`` converted to gibibytes,
         *             rounded to two decimals.
         *         nfo: Aggregate NFO status counts (valid / invalid / missing).
         *         repair_queue_pending: Number of ``repair_queue`` rows with
         *             ``status = 'pending'``.
         *         repair_queue_oldest_age_s: Age in seconds of the oldest pending
         *             repair-queue entry (based on ``enqueued_at``), or ``None`` when
         *             the queue is empty.
         *         outbox_pending: Number of ``outbox`` rows awaiting processing, or 0
         *             when the outbox table does not exist.
         *         outbox_oldest_age_s: Age in seconds of the oldest outbox entry
         *             (based on ``created_at``), or ``None`` when the outbox is empty.
         *         last_scan_id: Primary-key ``id`` of the most recent ``scan_run`` row,
         *             or ``None`` when no scan has ever been recorded.
         *         last_scan_mode: Scan mode of the most recent scan — one of
         *             ``"quick"``, ``"incremental"``, ``"enrich"``, ``"full"``,
         *             ``"verify"``, ``"repair"`` (the ``scan_run.mode`` CHECK
         *             constraint), or ``None``.
         *         last_scan_status: Final status of the most recent scan — one of
         *             ``"running"``, ``"ok"``, ``"failed"``, ``"aborted"`` (the
         *             ``scan_run.status`` CHECK constraint), or ``None``.
         *         last_scan_started_at: ISO 8601 UTC timestamp of when the most recent
         *             scan started, or ``None``.
         *         last_scan_finished_at: ISO 8601 UTC timestamp of when the most
         *             recent scan finished, or ``None``.
         *         last_scan_stuck: ``True`` when the most recent scan started more than
         *             a configurable threshold ago and hasn't finished — typically
         *             indicating a hung or killed scan process.
         *         soft_deleted: Count of soft-deleted ``media_file`` rows (where
         *             ``deleted_at IS NOT NULL``).
         *         canonical_null: Count of ``media_item`` rows where
         *             ``canonical_provider IS NULL``.
         *         degraded: ``True`` when the database file exists but a health query
         *             failed (e.g. a missing / mis-migrated table). In that case the
         *             counts are zeroed but this flag distinguishes a broken DB from a
         *             genuinely empty library. Defaults to ``False``.
         *         error: Optional error message describing the query failure when
         *             ``degraded`` is ``True``; ``None`` otherwise.
         */
        IndexHealthResponse: {
            /**
             * Canonical Null
             * @default 0
             */
            canonical_null: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Error */
            error?: string | null;
            /** Files */
            files: number;
            /** Items */
            items: number;
            /** Last Scan Finished At */
            last_scan_finished_at?: string | null;
            /** Last Scan Id */
            last_scan_id?: number | null;
            /** Last Scan Mode */
            last_scan_mode?: string | null;
            /** Last Scan Started At */
            last_scan_started_at?: string | null;
            /** Last Scan Status */
            last_scan_status?: string | null;
            /**
             * Last Scan Stuck
             * @default false
             */
            last_scan_stuck: boolean;
            /** Movies */
            movies: number;
            nfo: components["schemas"]["NfoStats"];
            /** Outbox Oldest Age S */
            outbox_oldest_age_s?: number | null;
            /** Outbox Pending */
            outbox_pending: number;
            /** Repair Queue Oldest Age S */
            repair_queue_oldest_age_s?: number | null;
            /** Repair Queue Pending */
            repair_queue_pending: number;
            /** Shows */
            shows: number;
            /** Size Gb */
            size_gb: number;
            /**
             * Soft Deleted
             * @default 0
             */
            soft_deleted: number;
        };
        /**
         * LockState
         * @description State of a single filesystem lock file.
         *
         *     Attributes:
         *         held: ``True`` when the lock file exists on disk.
         *         pid: The process ID read from the lock file, or ``None`` when the
         *             lock is not held or the PID couldn't be parsed.
         *         pid_alive: ``True`` when the PID reported in the lock file
         *             corresponds to a live process (checked via ``os.kill(pid, 0)``).
         *         stale: ``True`` when the lock file exists but the PID inside it is
         *             no longer alive — the lock should be cleaned up.
         *         age_s: Age of the lock file in seconds (``time.time() - mtime``),
         *             or ``None`` when the lock is not held.
         */
        LockState: {
            /** Age S */
            age_s?: number | null;
            /** Held */
            held: boolean;
            /** Pid */
            pid?: number | null;
            /**
             * Pid Alive
             * @default false
             */
            pid_alive: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /**
         * LocksResponse
         * @description Top-level response for the locks and orphans monitoring panel.
         *
         *     Attributes:
         *         pipeline_lock: State of the main ``pipeline.lock`` file.
         *         sentinels: State of the pause and watcher-paused sentinels.
         *         tmp_orphans: List of temporary orphan files or directories found
         *             during a bounded sweep (capped at 100 entries).
         */
        LocksResponse: {
            pipeline_lock: components["schemas"]["LockState"];
            sentinels: components["schemas"]["Sentinels"];
            /** Tmp Orphans */
            tmp_orphans: components["schemas"]["TmpOrphan"][];
        };
        /**
         * LoginRequest
         * @description Login request body.
         *
         *     Attributes:
         *         username: The username to authenticate.
         *         password: The plaintext password to verify.
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MaintenanceAction
         * @description A single maintenance action backed by a ``library-*`` CLI command.
         *
         *     Each entry in :data:`REGISTRY` maps 1:1 to a Typer-registered
         *     ``library-*`` command. The web UI reads the registry to render the
         *     action panels and the ``POST /api/maintenance/run`` endpoint uses it
         *     to validate incoming requests and build the subprocess invocation.
         *
         *     Attributes:
         *         id: Kebab-case CLI command name (e.g. ``"library-index"``).
         *         title: Short French label for the web UI action card / button.
         *         description: One-line French description of what the command does.
         *         category: UI grouping — ``"query"`` (read-only info), ``"scan"``
         *             (indexer scans), ``"repair"`` (repair-queue based fixes),
         *             ``"clean"`` (filesystem cleanup), ``"analyze"`` (insights),
         *             ``"fix"`` (targeted DB/filesystem repairs).
         *         risk: Write-impact classification — ``"ro"`` (read-only, safe to
         *             run anytime), ``"write"`` (mutates DB or filesystem but is
         *             reversible / non-destructive), ``"destructive"`` (deletes files,
         *             drops rows, or truncates data — needs confirmation UI).
         *         long_running: ``True`` when the command walks disks, makes network
         *             calls, or processes the full library. The web UI uses this to
         *             route execution through the S2 subprocess + lock path and show
         *             a progress indicator.
         *         dry_run: ``"supported"`` when the CLI exposes ``--dry-run`` or an
         *             ``--apply`` flag whose absence means dry-run. ``"unsupported"``
         *             otherwise. The web UI sends ``dry_run`` separately; this field
         *             tells it whether to show the toggle.
         *         options: Curated list of high-value targeting flags/arguments.
         *             Plumbing flags (``--config``, ``--db``, ``--wait-for-lock``,
         *             ``--confirm-bulk-change``, ``--list-checks``, ``--export``,
         *             ``--backfill-streams``, ``--rebuild``, ``--no-enqueue``,
         *             ``--interactive``, ``--read-only``, ``--enqueue-repairs``,
         *             ``--clean-fk-orphans``, ``--purge-unrecoverable``,
         *             ``--purge-release-orphans``, ``--from-index``, ``--fix``) are
         *             excluded — the web layer handles them separately or they are
         *             irrelevant outside a terminal.
         */
        MaintenanceAction: {
            /**
             * Category
             * @enum {string}
             */
            category: "query" | "scan" | "repair" | "clean" | "analyze" | "fix";
            /** Description */
            description: string;
            /**
             * Dry Run
             * @enum {string}
             */
            dry_run: "unsupported" | "supported";
            /** Id */
            id: string;
            /** Long Running */
            long_running: boolean;
            /** Options */
            options: components["schemas"]["ActionOption"][];
            /**
             * Risk
             * @enum {string}
             */
            risk: "ro" | "write" | "destructive";
            /** Title */
            title: string;
        };
        /**
         * NfoStats
         * @description Aggregate NFO file status counts across the indexed library.
         *
         *     Attributes:
         *         valid: Number of media items with a valid NFO file.
         *         invalid: Number of media items with a structurally invalid NFO file.
         *         missing: Number of media items without any NFO file.
         */
        NfoStats: {
            /** Invalid */
            invalid: number;
            /** Missing */
            missing: number;
            /** Valid */
            valid: number;
        };
        /**
         * PipelineOutcome
         * @description Final outcome of a completed (or killed) pipeline run.
         *
         *     Used in the ``pipeline_run.outcome`` column and the ``StatusResponse``
         *     for active runs.
         *
         *     Attributes:
         *         success: The run completed without errors.
         *         error: The run terminated with an unhandled error.
         *         killed: The run was killed via the ``/api/pipeline/kill`` endpoint.
         *         running: The run is still in progress.
         *         paused: The run is paused at a step boundary.
         * @enum {string}
         */
        PipelineOutcome: "success" | "error" | "killed" | "running" | "paused";
        /**
         * PipelineState
         * @description Current run-state of the pipeline process.
         *
         *     Attributes:
         *         idle: No pipeline run is in progress.
         *         running: A pipeline run is actively executing.
         *         paused: A pipeline run is in progress but paused at a step boundary.
         * @enum {string}
         */
        PipelineState: "idle" | "running" | "paused";
        /**
         * PutFileRequest
         * @description Request body for ``PUT /api/config/files/{name}``.
         *
         *     Attributes:
         *         values: Key-value pairs to write into the config file.
         *         base_sha256: Expected SHA-256 digest of the file before the write
         *             (used for optimistic concurrency control — 412 if mismatched).
         */
        PutFileRequest: {
            /** Base Sha256 */
            base_sha256: string;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * PutFileResponse
         * @description Response body for ``PUT /api/config/files/{name}``.
         *
         *     Attributes:
         *         warnings: Validation warnings from ``validate_candidate()``.
         *         restart_required: Whether the changes affect a key flagged in the
         *             restart-impact map.
         */
        PutFileResponse: {
            /** Restart Required */
            restart_required: boolean;
            /** Warnings */
            warnings: string[];
        };
        /**
         * RestartResponse
         * @description Response body for ``POST /api/config/restart-web``.
         *
         *     Attributes:
         *         status: Always ``"scheduled"`` — the restart has been handed off to
         *             the process manager.
         */
        RestartResponse: {
            /** Status */
            status: string;
        };
        /**
         * RunDetail
         * @description Full detail for a single pipeline run, including step timings.
         *
         *     Attributes:
         *         run_uid: Unique run identifier.
         *         trigger: What triggered the run.
         *         dry_run: Whether this was a dry run.
         *         started_at: ISO 8601 UTC timestamp of run start.
         *         ended_at: ISO 8601 UTC timestamp of run end, or ``None``.
         *         outcome: Final outcome, or ``None``.
         *         duration_s: Wall-clock duration in seconds, or ``None``.
         *         steps: Per-step timing records parsed from ``steps_json``.
         *         error: Error message if the run failed, or ``None``.
         *         kind: Run kind discriminator. ``"pipeline"`` for media pipeline runs,
         *             ``"maintenance"`` for maintenance action runs.  Defaults to
         *             ``"pipeline"``.
         *         command: CLI command name for maintenance runs (e.g.
         *             ``"library-clean"``), or ``None`` for pipeline runs.
         *         options_json: JSON-serialized CLI options for maintenance runs, or
         *             ``None`` for pipeline runs.
         *         output_tail: Tail of the subprocess stdout/stderr for maintenance
         *             runs (last ~2000 characters), or ``None`` for pipeline runs.
         */
        RunDetail: {
            /** Command */
            command?: string | null;
            /** Dry Run */
            dry_run: boolean;
            /** Duration S */
            duration_s?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Kind
             * @default pipeline
             */
            kind: string;
            /** Options Json */
            options_json?: string | null;
            outcome?: components["schemas"]["PipelineOutcome"] | null;
            /** Output Tail */
            output_tail?: string | null;
            /** Run Uid */
            run_uid: string;
            /** Started At */
            started_at: string;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepTiming"][];
            /** Trigger */
            trigger: string;
        };
        /**
         * RunRequest
         * @description Request body for ``POST /api/pipeline/run``.
         *
         *     Attributes:
         *         dry_run: If ``True``, the pipeline performs a dry run without
         *             mutating the filesystem.
         */
        RunRequest: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /**
         * RunSummary
         * @description Summary row for the pipeline run-history list endpoint.
         *
         *     Attributes:
         *         run_uid: Unique run identifier (uuid4 hex).
         *         trigger: What triggered the run (``"cli"``, ``"web"``, ``"watcher"``, etc.).
         *         dry_run: Whether this was a dry run.
         *         started_at: ISO 8601 UTC timestamp of run start.
         *         ended_at: ISO 8601 UTC timestamp of run end, or ``None`` if still
         *             running.
         *         outcome: Final outcome, or ``None`` if still in progress.
         *         duration_s: Wall-clock duration in seconds (``ended_at - started_at``),
         *             or ``None`` if either timestamp is missing.
         *         kind: Run kind discriminator. ``"pipeline"`` for media pipeline runs
         *             (ingest→sort→scrape→dispatch), ``"maintenance"`` for maintenance
         *             action runs (e.g. ``library-clean``).  Defaults to ``"pipeline"``.
         *         command: CLI command name for maintenance runs (e.g.
         *             ``"library-clean"``, ``"library-rescrape"``), or ``None`` for
         *             pipeline runs.
         */
        RunSummary: {
            /** Command */
            command?: string | null;
            /** Dry Run */
            dry_run: boolean;
            /** Duration S */
            duration_s?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Kind
             * @default pipeline
             */
            kind: string;
            outcome?: components["schemas"]["PipelineOutcome"] | null;
            /** Run Uid */
            run_uid: string;
            /** Started At */
            started_at: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * SecretEntry
         * @description A single secret key catalogued from ``.env.example``.
         *
         *     Attributes:
         *         key: Environment variable name (e.g. ``"TMDB_API_KEY"``).
         *         description: Human-readable description from the catalog comment.
         *         is_set: Whether the key has a value in ``.env``.
         */
        SecretEntry: {
            /** Description */
            description: string;
            /** Is Set */
            is_set: boolean;
            /** Key */
            key: string;
        };
        /**
         * SecretsPutRequest
         * @description Request body for ``PUT /api/config/secrets``.
         *
         *     Wraps a flat ``{KEY: value, ...}`` mapping. Keys must exist in the
         *     secret catalog (``.env.example``). Values are the new secret strings.
         */
        SecretsPutRequest: {
            [key: string]: string;
        };
        /**
         * SecretsResponse
         * @description Response body for ``GET /api/config/secrets``.
         *
         *     Attributes:
         *         secrets: All secret entries from the catalog. Values are never
         *             included.
         */
        SecretsResponse: {
            /** Secrets */
            secrets: components["schemas"]["SecretEntry"][];
        };
        /**
         * Sentinels
         * @description State of the pause and watcher-paused sentinel files.
         *
         *     These are not traditional locks — they signal the pipeline engine to
         *     pause at the next step boundary or to disable the directory watcher.
         *
         *     Attributes:
         *         pause: ``True`` when ``data_dir/pipeline.pause`` exists.
         *         pause_age_s: Age of the pause sentinel in seconds, or ``None`` when
         *             it does not exist.
         *         watcher_paused: ``True`` when ``data_dir/watcher.paused`` exists.
         *         watcher_paused_age_s: Age of the watcher-paused sentinel in seconds,
         *             or ``None`` when it does not exist.
         */
        Sentinels: {
            /**
             * Pause
             * @default false
             */
            pause: boolean;
            /** Pause Age S */
            pause_age_s?: number | null;
            /**
             * Watcher Paused
             * @default false
             */
            watcher_paused: boolean;
            /** Watcher Paused Age S */
            watcher_paused_age_s?: number | null;
        };
        /**
         * StatusResponse
         * @description Response body for ``GET /api/pipeline/status``.
         *
         *     Reflects the live state of the pipeline engine, the pause sentinel,
         *     the watcher sentinel, and the latest run metadata.
         *
         *     Attributes:
         *         state: The current pipeline run-state.
         *         run_uid: The unique identifier of the latest or active run, or
         *             ``None`` when idle.
         *         step: The human-readable name of the current step, or ``None``
         *             when idle.
         *         paused: Whether the pipeline is currently paused at a step boundary.
         *         watcher_enabled: Whether the directory watcher is currently active.
         *         pid: The OS process ID of the running pipeline subprocess, or
         *             ``None`` when idle.
         */
        StatusResponse: {
            /** Paused */
            paused: boolean;
            /** Pid */
            pid?: number | null;
            /** Run Uid */
            run_uid?: string | null;
            state: components["schemas"]["PipelineState"];
            /** Step */
            step?: string | null;
            /** Watcher Enabled */
            watcher_enabled: boolean;
        };
        /**
         * StepTiming
         * @description Timing record for a single pipeline step within a run.
         *
         *     Attributes:
         *         name: Human-readable step name (e.g. ``"ingest"``, ``"sort"``).
         *         status: Step status (``"done"``, ``"running"``, ``"error"``, etc.).
         *         started_at: ISO 8601 UTC timestamp of step start, or ``None``.
         *         ended_at: ISO 8601 UTC timestamp of step end, or ``None``.
         *         elapsed_s: Step duration in seconds, or ``None`` if either timestamp
         *             is missing.
         */
        StepTiming: {
            /** Elapsed S */
            elapsed_s?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /**
         * TmpOrphan
         * @description A single temporary orphan entry found during a bounded filesystem sweep.
         *
         *     Matched by prefix (``_tmp_dispatch_*``, ``_tmp_ingest_*``) and reported
         *     up to a hard cap of 100 entries.
         *
         *     Attributes:
         *         path: Absolute or relative path to the orphan entry.
         *         prefix: The matched prefix (``"_tmp_dispatch_"`` or
         *             ``"_tmp_ingest_"``).
         *         age_s: Age of the orphan entry in seconds (``time.time() - mtime``).
         */
        TmpOrphan: {
            /** Age S */
            age_s: number;
            /** Path */
            path: string;
            /** Prefix */
            prefix: string;
        };
        /**
         * ValidateRequest
         * @description Request body for ``POST /api/config/validate``.
         *
         *     Attributes:
         *         file_name: Config file basename to validate against.
         *         values: Candidate key-value pairs to validate.
         */
        ValidateRequest: {
            /** File Name */
            file_name: string;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * ValidateResponse
         * @description Response body (200) for ``POST /api/config/validate``.
         *
         *     Attributes:
         *         warnings: Validation warnings returned by ``validate_candidate()``.
         */
        ValidateResponse: {
            /** Warnings */
            warnings: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Response model for the version endpoint.
         *
         *     Attributes:
         *         version: The Python package version string.
         *         build_commit: The deployed git SHA, or ``"dev"``.
         */
        VersionResponse: {
            /** Build Commit */
            build_commit: string;
            /** Version */
            version: string;
        };
        /**
         * WatcherRequest
         * @description Request body for ``POST /api/pipeline/watcher``.
         *
         *     Attributes:
         *         enabled: If ``True``, enable the directory watcher; if ``False``,
         *             pause it.
         */
        WatcherRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * WatcherResponse
         * @description Response body for ``POST /api/pipeline/watcher``.
         *
         *     Attributes:
         *         watcher_enabled: Whether the directory watcher is now enabled.
         */
        WatcherResponse: {
            /** Watcher Enabled */
            watcher_enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_files_api_config_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilesResponse"];
                };
            };
        };
    };
    get_file_api_config_files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_file_api_config_files__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutFileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_web_api_config_restart_web_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    get_schema_api_config_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSchemaResponse"];
                };
            };
        };
    };
    get_secrets_api_config_secrets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
        };
    };
    put_secrets_api_config_secrets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsPutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_config_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigStatusResponse"];
                };
            };
        };
    };
    validate_file_api_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_actions_api_maintenance_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsResponse"];
                };
            };
        };
    };
    action_run_api_maintenance_actions__action_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disks_api_maintenance_disks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisksResponse"];
                };
            };
        };
    };
    get_index_health_api_maintenance_index_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexHealthResponse"];
                };
            };
        };
    };
    get_locks_api_maintenance_locks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocksResponse"];
                };
            };
        };
    };
    pipeline_history_api_pipeline_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: string;
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_history_detail_api_pipeline_history__run_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_kill_api_pipeline_kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    pipeline_pause_api_pipeline_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    pipeline_resume_api_pipeline_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    pipeline_run_api_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_status_api_pipeline_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    pipeline_watcher_api_pipeline_watcher_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatcherRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatcherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
