/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and set a session cookie.
         *
         *     Verifies the supplied credentials against the stored scrypt hash.  On
         *     success, creates a JWT session token and sets it as an HttpOnly,
         *     SameSite=Strict cookie.  On failure, returns 401 after a small constant
         *     delay (to deter timing-based user enumeration).
         *
         *     Args:
         *         body: The login credentials (username + password).
         *         request: The incoming FastAPI request (for app.state access).
         *
         *     Returns:
         *         A ``Response`` with status 204 and a ``Set-Cookie`` header on success.
         *
         *     Raises:
         *         HTTPException: 401 if the credentials are invalid or the password
         *             hash has not been configured.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie (log out).
         *
         *     Requires a valid session (guarded by ``require_session``).
         *
         *     Args:
         *         session: The authenticated session injected by the guard.
         *
         *     Returns:
         *         A ``Response`` with status 204 and a cookie-clearing ``Set-Cookie`` header.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's identity.
         *
         *     Requires a valid session (guarded by ``require_session``).
         *
         *     Args:
         *         session: The authenticated session injected by the guard.
         *
         *     Returns:
         *         A dict with the ``username`` key.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health-check endpoint — reachable, Redis, and DB presence.
         *
         *     Both probes are **fail-soft**: they never raise and never block boot.
         *     A down Redis or missing DB returns ``false`` for that key, not a 5xx.
         *
         *     Returns:
         *         A dict with:
         *         - **status**: Always ``"ok"`` if this handler is reachable.
         *         - **redis**: ``True`` if the configured Redis instance responds to PING.
         *         - **db**: ``True`` if ``library.db`` exists at the configured data_dir path.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Application version endpoint.
         *
         *     Returns:
         *         A dict with ``version`` (the Python package version) and
         *         ``build_commit`` (the deployed git SHA, or ``"dev"``).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health-check endpoint.
         *
         *     Attributes:
         *         status: Always ``"ok"`` if the handler is reachable.
         *         redis: ``True`` if the configured Redis instance responds to PING.
         *         db: ``True`` if ``library.db`` exists at the configured data_dir path.
         */
        HealthResponse: {
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
            /** Status */
            status: string;
        };
        /**
         * LoginRequest
         * @description Login request body.
         *
         *     Attributes:
         *         username: The username to authenticate.
         *         password: The plaintext password to verify.
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionResponse
         * @description Response model for the version endpoint.
         *
         *     Attributes:
         *         version: The Python package version string.
         *         build_commit: The deployed git SHA, or ``"dev"``.
         */
        VersionResponse: {
            /** Build Commit */
            build_commit: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
