"""Characterization pins for the scraper post-match write-back (P0.5).

Locks the CURRENT behaviour of the canonical write path shared by the
automatic scrape and the operator-forced resolve — folder rename, video /
episode rename, ``<title>`` / ``<year>`` / ``<uniqueid>`` NFO fields, and the
set of artwork files that land next to the media — so any later thin refactor
of ``_write_confirmed_movie`` / ``_write_confirmed_show`` that changes an
observable output trips a golden mismatch instead of shipping silently. This
file changes ZERO production code; it only observes.

Golden mechanics mirror :mod:`tests.verify.test_characterization_golden`:

* Run-mode (default): load each golden JSON and assert an exact match. A
  missing golden **fails** the test (never skips) — a vanished baseline must
  not mask a regression.
* Capture-mode (``CAPTURE_GOLDEN=1``): (re)write the golden files from the
  CURRENT code. The committed goldens are never auto-regenerated by a normal
  run.

The write path reaches the network only through the provider clients and the
artwork downloader; both are stubbed here (fake providers via ``mock_registry``,
``download_image`` replaced by a local stub that writes deterministic bytes), so
the suite is fully hermetic — no TMDB/TVDB, no ffprobe, no real staging.
"""

from __future__ import annotations

import json
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

from personalscraper.core.event_bus import EventBus
from personalscraper.naming_patterns import NamingPatterns
from personalscraper.scraper.confidence import MatchResult
from personalscraper.scraper.orchestrator import Scraper

GOLDEN_DIR = Path(__file__).parent / "golden"
_CAPTURE = os.environ.get("CAPTURE_GOLDEN") == "1"


# ---------------------------------------------------------------------------
# Provider payloads (fake providers — never real TMDB/TVDB)
# ---------------------------------------------------------------------------

# One movie identity, reused by the automatic AND forced paths so the
# forced-vs-automatic invariant compares like-for-like (same match).
_MOVIE_DATA: dict[str, Any] = {
    "id": 603,
    "title": "The Matrix",
    "original_title": "The Matrix",
    "name": "The Matrix",
    "original_name": "The Matrix",
    "overview": "A hacker learns the truth about his reality.",
    "vote_average": 8.2,
    "vote_count": 20000,
    "genres": [{"name": "Action"}],
    "release_date": "1999-03-31",
    "credits": {"cast": [], "crew": []},
    "images": {
        "posters": [{"file_path": "/matrix-poster.jpg", "iso_639_1": "en", "vote_average": 7.0}],
        "backdrops": [{"file_path": "/matrix-backdrop.jpg", "iso_639_1": None, "vote_average": 8.0}],
        "logos": [],
    },
    "external_ids": {"imdb_id": "tt0133093"},
    "release_dates": {"results": []},
    "production_countries": [],
    "production_companies": [],
    "origin_country": [],
}

_MOVIE_TMDB_ID = 603


def _movie_match() -> MatchResult:
    """Return the high-confidence match the automatic path selects for the movie."""
    return MatchResult(api_id=_MOVIE_TMDB_ID, api_title="The Matrix", api_year=1999, confidence=0.95, source="tmdb")


# ---------------------------------------------------------------------------
# Hermetic download stub + snapshot helpers
# ---------------------------------------------------------------------------


def _fake_download_image(url: str, dest: Path) -> bool:
    """Stand in for ``ArtworkDownloader.download_image`` without any network.

    Writes deterministic placeholder bytes to *dest* (creating parents) so the
    real ``download_movie_artwork`` / ``download_tvshow_artwork`` naming logic
    runs end-to-end and the resulting artwork files actually land next to the
    media — exactly what the snapshot pins — while staying fully offline.

    Args:
        url: Source URL (ignored; kept for signature parity).
        dest: Destination path the downloader computed via ``NamingPatterns``.

    Returns:
        Always ``True`` (a successful "download"), matching the contract the
        downloader relies on to append *dest* to its returned list.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(b"stub-image")
    return True


def _tree(media_path: Path) -> list[str]:
    """Return the sorted relative paths of every file under *media_path*.

    Pins the write-back's filesystem shape (renamed video/episodes, NFO
    presence, the artwork set) without capturing volatile file *contents* —
    only the deterministic names and layout.
    """
    return sorted(str(p.relative_to(media_path)) for p in media_path.rglob("*") if p.is_file())


def _nfo_pins(nfo_path: Path) -> dict[str, Any]:
    """Extract the stable identity pins from an NFO file.

    Captures ``<title>``, ``<year>`` and each ``<uniqueid>`` (id text + type +
    ``default`` flag). These are the fields dispatch/verify key on; volatile
    fields (dates already deterministic in the fixtures, generator block) are
    intentionally not pinned here.

    Args:
        nfo_path: Path to the NFO file to parse.

    Returns:
        A JSON-able dict with ``title``, ``year`` and a ``uniqueids`` map
        keyed by ``type``.
    """
    root = ET.parse(nfo_path).getroot()
    uniqueids = {u.get("type"): {"id": u.text, "default": u.get("default")} for u in root.findall("uniqueid")}
    return {
        "title": root.findtext("title"),
        "year": root.findtext("year"),
        "uniqueids": uniqueids,
    }


def _movie_snapshot(media_path: Path) -> dict[str, Any]:
    """Normalized write-back snapshot for a movie directory."""
    nfo = next(media_path.glob("*.nfo"))
    return {
        "folder": media_path.name,
        "tree": _tree(media_path),
        "nfo": _nfo_pins(nfo),
    }


def _check_golden(name: str, actual: dict[str, Any], *, golden_dir: Path = GOLDEN_DIR) -> None:
    """Capture or assert one normalized snapshot against its golden JSON.

    Mirrors :func:`tests.verify.test_characterization_golden._check`: in
    capture mode writes the golden; otherwise asserts the golden EXISTS
    (fail-on-missing, never skip) then asserts an exact match.

    Args:
        name: Golden basename (``<name>.json``).
        actual: The JSON-able snapshot produced by the current code.
        golden_dir: Directory holding the golden files (overridable so the
            fail-on-missing behaviour is itself testable against a tmp dir).
    """
    path = golden_dir / f"{name}.json"
    if _CAPTURE:
        golden_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(actual, indent=2, sort_keys=True))
        return
    assert path.exists(), f"Golden {name}.json MISSING — capture it (CAPTURE_GOLDEN=1) before asserting"
    assert actual == json.loads(path.read_text()), f"Golden mismatch for {name}"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def scraper(mock_registry: Any) -> Scraper:
    """A registry-backed Scraper with no config (classification skipped).

    Reuses the ``mock_registry`` fake-provider family from the scraper
    conftest — the closest existing fixture — instead of inventing a new
    fake-TMDB. ``event_bus`` is a real :class:`EventBus` (never ``None``).
    """
    settings = MagicMock()
    settings.tmdb_api_key = "fake-key"
    settings.tvdb_api_key = "fake-key"
    with patch("personalscraper.api.metadata.tmdb.TMDBClient"):
        return Scraper(settings, NamingPatterns(), event_bus=EventBus(), registry=mock_registry)


# ---------------------------------------------------------------------------
# Movie write-back pins
# ---------------------------------------------------------------------------


def _run_automatic_movie(scraper: Scraper, movie_dir: Path) -> Any:
    """Drive the automatic ``scrape_movie`` path with fake providers + stubbed I/O."""
    with (
        patch("personalscraper.scraper.confidence.match_movie_detailed", return_value=(_movie_match(), [])),
        patch.object(scraper._registry.get("tmdb"), "get_movie", return_value=_MOVIE_DATA),
        patch("personalscraper.scraper.scraper.extract_stream_info", return_value=None),
        patch.object(scraper._artwork, "download_image", side_effect=_fake_download_image),
    ):
        return scraper.scrape_movie(movie_dir)


def test_movie_writeback_pins(scraper: Scraper, tmp_path: Path) -> None:
    """A raw movie folder scrapes to canonical folder + video + NFO ids + artwork.

    Pins (against ``golden/movie_writeback.json``): the final ``Title (Year)``
    folder name, the renamed ``Title.ext`` video, the movie NFO ``<title>`` /
    ``<year>`` / ``<uniqueid>`` (imdb ``default="true"`` + tmdb), and the poster
    + landscape artwork files that land next to the media.
    """
    movie_dir = tmp_path / "the.matrix.1999.1080p.BluRay.x264-GROUP"
    movie_dir.mkdir()
    (movie_dir / "the.matrix.1999.1080p.BluRay.x264-GROUP.mkv").write_bytes(b"\x00")

    result = _run_automatic_movie(scraper, movie_dir)

    assert result.action == "scraped", result.error
    snapshot = _movie_snapshot(result.media_path)
    _check_golden("movie_writeback", snapshot)


def test_missing_golden_fails_not_skips(tmp_path: Path) -> None:
    """A missing golden must FAIL (AssertionError), never silently pass/skip."""
    if _CAPTURE:
        pytest.skip("capture mode writes goldens instead of asserting")
    with pytest.raises(AssertionError, match="MISSING"):
        _check_golden("does_not_exist", {"any": "value"}, golden_dir=tmp_path / "empty")
