"""Decision run reservation — the per-decision concurrency guard.

Thin shim over :func:`personalscraper.web._runner_engine.reserve_run_row` (the
single ``BEGIN IMMEDIATE`` + INSERT owner). This module supplies only the
per-decision concurrency *guard*: a second concurrent resolve POST **for the same
decision** blocks on the write lock, then observes the freshly-inserted running
row and gets 409. Resolves of DIFFERENT decisions do not block each other — the
guard is scoped to ``decision_id`` (webui-ux phase 4).

Route-side (runs in the web process before the 202 response). The reserved row is
claimed with the web process's pid (guaranteed alive) — the caller updates it to
the spawned runner's pid right after spawn (R8).
"""

from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path

from fastapi import HTTPException

from personalscraper.logger import get_logger
from personalscraper.web._runner_engine import reserve_run_row

log = get_logger(__name__)


def _guard_no_running_resolve(conn: sqlite3.Connection, decision_id: int) -> None:
    """Raise 409 when a live scrape-resolve for *decision_id* is already running.

    Queries ``pipeline_run`` for rows with ``kind='maintenance'``,
    ``command='scrape-resolve'``, ``outcome='running'``, AND
    ``json_extract(options_json, '$.decision_id') = decision_id`` — the guard is
    scoped to THIS decision so two DIFFERENT decisions resolve concurrently
    (webui-ux phase 4), while a double-launch of the SAME decision still 409s.
    Liveness is checked via ``os.kill(pid, 0)``; rows with a dead or NULL pid are
    stale (crashed runner / pre-pid migration) and are ignored — we never mutate
    them here.

    Same-staging-path exclusivity across two distinct decision rows is enforced
    one layer down by :func:`personalscraper.lock.acquire_scrape_resolve_lock`
    (sha1 of the staging path), so this per-``decision_id`` reservation guard and
    the per-item CLI lock together cover both the same-decision and same-path
    races.

    Args:
        conn: An open connection (inside the reserve transaction).
        decision_id: The ``scrape_decision.id`` being resolved — the guard is
            scoped to running resolves of THIS decision only.

    Raises:
        HTTPException: 409 when a live scrape-resolve runner for *decision_id* is
            found.
    """
    rows = conn.execute(
        "SELECT run_uid, pid FROM pipeline_run "
        "WHERE kind='maintenance' AND command='scrape-resolve' AND outcome='running' "
        "AND json_extract(options_json, '$.decision_id') = ?",
        (decision_id,),
    ).fetchall()
    for row in rows:
        run_uid_db = row["run_uid"]
        pid_db = row["pid"]
        if pid_db is None:
            # NULL pid → stale row (pre-pid-migration or a runner that crashed
            # before claiming its pid).
            log.info("resolve_stale_row_ignored", run_uid=run_uid_db, pid=None)
            continue
        try:
            os.kill(pid_db, 0)
        except ProcessLookupError:
            # Dead process → stale row (crashed runner).
            log.info("resolve_stale_row_ignored", run_uid=run_uid_db, pid=pid_db)
            continue
        except PermissionError:
            # Process exists but owned by another user → treat as alive.
            raise HTTPException(status_code=409, detail="This decision is already resolving")
        else:
            raise HTTPException(status_code=409, detail="This decision is already resolving")


def _reserve_decision_run(
    db_path: Path,
    *,
    run_uid: str,
    decision_id: int,
    provider: str,
    provider_id: int,
) -> None:
    """Atomically guard per-decision concurrency and reserve a ``pipeline_run`` row.

    Delegates the ``BEGIN IMMEDIATE`` + INSERT to the shared engine, passing
    :func:`_guard_no_running_resolve` as the concurrency guard so the check and
    the insert are a single serialised transaction. Fail-CLOSED on a DB error
    (409 ``'Cannot verify'``) — a resolve WRITES to staging and must never proceed
    without concurrency protection (Finding E).

    Row shape (canonical): ``kind='maintenance'``, ``command='scrape-resolve'``,
    ``options_json={"decision_id": N, "provider": "…", "provider_id": N}`` (sorted
    keys, compact separators), ``trigger='web'``, ``dry_run=0``,
    ``outcome='running'``, ``pid=os.getpid()`` (replaced by caller after spawn).

    Args:
        db_path: Absolute path to ``library.db``.
        run_uid: The unique run identifier, generated by the caller.
        decision_id: The ``scrape_decision.id`` being resolved.
        provider: Metadata provider name (``'tmdb'`` or ``'tvdb'``).
        provider_id: Numeric identifier assigned by the provider.

    Raises:
        HTTPException: 409 when a scrape-resolve for THIS ``decision_id`` is
            already running with a live pid, or when the DB cannot be read to
            verify concurrency.
    """
    options = {"decision_id": decision_id, "provider": provider, "provider_id": provider_id}
    options_json = json.dumps(options, sort_keys=True, separators=(",", ":"))

    reserve_run_row(
        db_path,
        run_uid=run_uid,
        kind="maintenance",
        command="scrape-resolve",
        options_json=options_json,
        dry_run=False,
        guard=lambda conn: _guard_no_running_resolve(conn, decision_id),
        fail_closed=True,
        fail_closed_detail="Cannot verify no scrape-resolve is running",
    )
