"""Characterization golden — parity proof for the check-plugins refactor.

Run-mode (default): load each golden JSON and assert BYTE-IDENTICAL output from
every public entry point. FAILS (does not skip) if a golden file is missing —
a vanished baseline must never mask a regression.

Capture-mode (CAPTURE_GOLDEN=1): (re)write the golden files from the CURRENT code.
Run ONCE on pre-refactor HEAD in Phase 0; re-run selectively in Phase 7 via
GOLDEN_ONLY=verifier_movie,verifier_tvshow for the deliberate fix-policy change.

The golden files are committed and NEVER auto-regenerated by a normal test run.
"""

from __future__ import annotations

import dataclasses
import json
import os
import re
import sqlite3
from collections.abc import Callable
from pathlib import Path
from typing import Any

from personalscraper.conf.models.config import Config
from personalscraper.config import Settings
from personalscraper.core.event_bus import EventBus
from personalscraper.enforce.coherence_checker import check_coherence
from personalscraper.naming_patterns import PATTERNS
from personalscraper.verify.checker import MediaChecker
from personalscraper.verify.library_checks import validate_from_index, validate_library
from personalscraper.verify.verifier import Verifier
from tests.verify.golden import _corpus

GOLDEN_DIR = Path(__file__).parent / "golden"
_CAPTURE = os.environ.get("CAPTURE_GOLDEN") == "1"
_ONLY = set(filter(None, os.environ.get("GOLDEN_ONLY", "").split(",")))

# Fields that are non-deterministic and must be normalized out before compare.
_DROP_KEYS = {"validated_at"}

# Pattern that matches a pytest tmp_path prefix — independent of the absolute
# base (/private/tmp on this host, /tmp on Linux CI, /private/var/folders on
# some macOS) and of the optional pytest-xdist worker segment (popen-gwN/).
# Normalizing to a fixed token keeps the goldens deterministic across OSes,
# serial vs parallel runs, and worker counts.
_TMP_PATH_RE = re.compile(r".*?/pytest-of-[^/]+/pytest-\d+/(?:popen-gw\d+/)?")


def _settings_stub() -> Settings:
    """Return a typed Settings stub (not a MagicMock) for Verifier construction."""
    from tests.fixtures.settings_stub import make_typed_settings_stub

    return make_typed_settings_stub()


def _ser(obj: Any) -> Any:
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        return {k: _ser(v) for k, v in dataclasses.asdict(obj).items() if k not in _DROP_KEYS}
    if isinstance(obj, dict):
        return {k: _ser(v) for k, v in obj.items() if k not in _DROP_KEYS}
    if isinstance(obj, (list, tuple)):
        return [_ser(i) for i in obj]
    if hasattr(obj, "value"):  # Enum
        return obj.value
    if isinstance(obj, str):
        return _TMP_PATH_RE.sub("{tmp}/", obj)
    if isinstance(obj, Path):
        return _TMP_PATH_RE.sub("{tmp}/", str(obj))
    return obj


def _check(name: str, produce: Callable[[], Any]) -> None:
    """Capture or assert one entry point. produce() -> JSON-able structure."""
    if _ONLY and name not in _ONLY:
        return
    path = GOLDEN_DIR / f"{name}.json"
    actual = _ser(produce())
    if _CAPTURE:
        path.write_text(json.dumps(actual, indent=2, sort_keys=True))
        return
    assert path.exists(), f"Golden {name}.json MISSING — capture it (CAPTURE_GOLDEN=1) before asserting"
    assert actual == json.loads(path.read_text()), f"Golden mismatch for {name}"


def test_checker_movie(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``MediaChecker.check_movie`` over the flat movie corpus."""
    items = _corpus.build_item_corpus(tmp_path / "c_mov")
    chk = MediaChecker(PATTERNS, test_config)
    _check("checker_movie", lambda: {n: chk.check_movie(p) for n, p in items.items() if n.startswith("movie_")})


def test_checker_tvshow(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``MediaChecker.check_tvshow`` over the flat TV show corpus."""
    items = _corpus.build_item_corpus(tmp_path / "c_tv")
    chk = MediaChecker(PATTERNS, test_config)
    _check("checker_tvshow", lambda: {n: chk.check_tvshow(p) for n, p in items.items() if n.startswith("tvshow_")})


def test_verifier_movie(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``Verifier.verify_movie`` over the flat movie corpus (fix=True)."""

    def produce() -> dict[str, Any]:
        out: dict[str, Any] = {}
        for n, p in _corpus.build_item_corpus(tmp_path / "v_mov").items():
            if n.startswith("movie_"):
                v = Verifier(_settings_stub(), PATTERNS, test_config, dry_run=False, fix=True)
                out[n] = v.verify_movie(p)
        return out

    _check("verifier_movie", produce)


def test_verifier_tvshow(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``Verifier.verify_tvshow`` over the flat TV show corpus (fix=True)."""

    def produce() -> dict[str, Any]:
        out: dict[str, Any] = {}
        for n, p in _corpus.build_item_corpus(tmp_path / "v_tv").items():
            if n.startswith("tvshow_"):
                v = Verifier(_settings_stub(), PATTERNS, test_config, dry_run=False, fix=True)
                out[n] = v.verify_tvshow(p)
        return out

    _check("verifier_tvshow", produce)


def test_library_validate(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``validate_library`` over the disk-layout corpus (fix+apply)."""
    cfg = _corpus.build_disk_corpus(tmp_path / "disk", test_config)  # returns a Config with a disk at tmp
    _check("library_validate", lambda: validate_library(cfg, fix=True, apply=True))


def test_library_from_index(tmp_path: Path) -> None:
    """Capture or assert ``validate_from_index`` over the seeded index DB."""
    conn = sqlite3.connect(":memory:")
    _corpus.seed_index_db(conn)
    _check("library_from_index", lambda: validate_from_index(conn))


def test_coherence(test_config: Config, tmp_path: Path) -> None:
    """Capture or assert ``check_coherence`` over the staging-layout corpus."""
    cfg = _corpus.build_staging_corpus(tmp_path / "stg", test_config)  # Config with paths.staging_dir at tmp
    _check("coherence", lambda: check_coherence(_settings_stub(), cfg, bus=EventBus()))
