"""The ceiling's ledger — which files are over it, who owes the reduction, and how much.

WHY IT IS ITS OWN FILE. `check-frontend-boundaries.py` reached 1 026 non-blank
lines against a hard ceiling of 1 000 when B-306's count was added to the size
arm, and what L07-bis and L14 both did about exactly that is the rule here: **a
guard is split on a SUBJECT, never on a line count.** The subject here is a
ledger — the list of files the ceiling forgives, the lot that still owes each
reduction, the size it was last recorded at, and the two documents that say
which lots exist and which have landed. None of that is about the module graph,
which is what the guard that imports this file is about.

WHAT LIVES HERE AND WHY IT TRAVELS TOGETHER. The list, the label's grammar, the
recorded counts, and the reader of the plan and the advancement are ONE subject:
every one of them exists to answer « does this entry still promise something ».
Splitting them would have left the reader of `IMPLEMENTATION.md` in one file and
the labels it judges in another, which is the arrangement that let `L09` sit at
`NOT STARTED` for a whole wave.

WHAT DOES NOT LIVE HERE. `arm_size` itself — it measures the tree, and measuring
the tree is the guard's. This file holds no `Path` walk and reads no source file
of the maquette.
"""
from __future__ import annotations

import re
from pathlib import Path


# Files over the block ceiling, each with the lot that OWES the reduction. The
# membership is generated by `--arm size --list-grandfathered`, never
# maintained by hand: a list typed out drifts from the tree it describes, and
# this repository has already watched a hand-kept number drift by seven inside
# the pull request that introduced it as a control.
#
# THE LABEL IS NOT A COMMENT, and it used not to be read at all (B-073). The
# arm was careful about the list's composition — it refuses a file over the
# ceiling with no entry, and an entry for a file back under it — and never once
# looked at the VALUE. Four entries named L07 for two waves after L07 landed,
# and all four had GROWN in it. A label naming a lot that has already landed
# promises a reduction nobody owes any more.
#
# So the value names the lot that STILL owes it, and only that lot. « L07, then
# L09 » was the shape that hid the defect: a label carrying two lots, one spent
# and one owed, with nothing to say which was which.
# A file NOBODY WRITES is not a module of this tree, and the size ceiling does
# not apply to it. Invariant 6's reason is « an agent modifying a component
# opens one file »; a generated artefact is opened by no one and edited by no
# one, so a ceiling on it would say nothing about the tree's health and would
# only ever be answered by a grandfather entry promising a reduction nobody
# owes.
#
# WHAT MAKES THIS EXEMPTION SAFE RATHER THAN A HOLE, and it is the whole
# difference: it is not a path someone may add themselves to. The value names
# the command that produces the file and the two checks that hold it — one
# regenerating it byte for byte where the generator is installed, one holding it
# against the contract by structure wherever this guard runs. Naming only the
# first left the exemption unproven on every machine that reads it, which is the
# same distance between a proof and a claim the whole lot is about.
GENERATED = {
    "contract/types.d.ts": (
        "npm run generate-contract-types — from frontend/maquette/contract/openapi.json. Held two ways: `make check-contract-types` regenerates it and refuses any difference, which needs the generator and runs only where it is installed; and `scripts/check-mock-seeds.py --arm generated` holds it against the contract by structure, needs neither node nor the generator, and runs wherever the guards do — which is where THIS exemption is read."
    ),
}

# AN ENTRY IS A LABEL **AND A COUNT**, and the count is B-306's whole subject.
# The label said WHO owed the reduction and nothing said the reduction was
# happening: a grandfathered file could grow without limit and this arm printed
# clean. It did — L14 added 68 non-blank lines to `engine/legacy.js` and 9 to
# `engine/states.js`, both labelled « dies by subtraction », and the guard had
# nothing to say about either.
#
# So each entry records the file's non-blank line count, measured exactly as
# this arm measures a file, and the arm compares:
#
#   above the record  → a violation, naming the file, the record and the reading
#   below the record  → PRINTED, with « re-record it », and the re-recording
#                       belongs to the SAME COMMIT that subtracts. A count
#                       re-recorded later is a count nobody compared.
#
# The two readings cannot drift apart by definition, because the record is
# produced by `--arm size --list`, which measures with the loop below.
#
# WHY BELOW IS NOT A VIOLATION. A ratchet that refused a shrink would refuse
# exactly the work the label exists to demand. What must not be silent is the
# STALENESS: a record that no longer describes the file is a record nobody
# compared, so it is printed on every run rather than discovered at an audit.
GRANDFATHERED = {
    "engine/legacy.js": ("L13 — the engine dies by subtraction, surface by surface", 32286),
    "engine/states.js": ("L13 — the scenario table goes with the engine it drives", 789),
}


def grandfathered_label(module: str) -> str:
    """The lot that owes a grandfathered file's reduction.

    Args:
        module: The file's path, as `GRANDFATHERED` writes it.

    Returns:
        The entry's label.
    """
    return GRANDFATHERED[module][0]


def grandfathered_count(module: str) -> int:
    """The non-blank line count a grandfathered file was last recorded at.

    Args:
        module: The file's path, as `GRANDFATHERED` writes it.

    Returns:
        The recorded count.
    """
    return GRANDFATHERED[module][1]

# A LABEL IS HELD AGAINST TWO DOCUMENTS, because since 2026-08-28 the answer
# lives in two. The plan declares WHICH lots exist and in what order; it carries
# no status at all, deliberately — a lot's progress written in two places is a
# lot's progress wrong in one of them, and it was: `L09` sat at `NOT STARTED` on
# `main` for a whole wave after it landed, and that stale word is what kept four
# entries promising a reduction L09 had been and gone without making. So the
# advancement is read where it now exists ALONE, `IMPLEMENTATION.md`'s
# « Landed, in order » row, and the plan is read only for the lots it declares.
#
# `#### L07 — Tailwind and CVA, surface by surface · *depended on L02, L04, L06*`
# `| **Landed, in order**  | L01 · L02 · … |`
#
# THE WHOLE CELL IS READ, not a leading run of it. The row's job is to name the
# lots that have landed, so anything lot-shaped inside it is one of them; a
# grammar that read « the part before the commentary » would be one more rule to
# keep true, and this arm's own history is a list of holds that stopped
# describing what they read.
#
# ANCHORED ON THESE FILES, not on the working directory. `--root` exists so the
# arms can be pointed at a copy of the tree, and the tests do exactly that from
# a scratch directory — but the plan and the advancement are one document each
# wherever the corpus is. A relative path here made the arm exit 1 from any
# directory but the repository root, blaming the plan for being unreadable:
# « unreadable is a violation » turns a wrong path into a hard failure with a
# message that names the wrong culprit.
# The repository root, so a path can be NAMED the way the allowance list
# writes it whatever the checkout is called.
REPOSITORY = Path(__file__).resolve().parent.parent
PLAN = REPOSITORY / "docs" / "reference" / "frontend-architecture.md"
ADVANCEMENT = REPOSITORY / "IMPLEMENTATION.md"
LOT_HEADING = re.compile(r"^####\s+(L\d\d)\b", re.M)
LANDED_ROW = re.compile(r"^\|\s*\*\*Landed, in order\*\*\s*\|([^|]*)", re.M)
LOT_CODE = re.compile(r"\bL\d\d\b")

# THE LABEL'S GRAMMAR: the lot that OWES the reduction, then a dash, then why.
# Anchored at the start on purpose. A label may go on to mention a lot that has
# already run — « L09 … (L07 converted the surface) » is worth keeping, because
# the reader wants to know a conversion already happened — and reading every
# mention would refuse exactly that sentence. What may never be spent is the
# lot the entry LEADS with: that one is the promise.
#
# « L07, then L09 » is the shape this refuses, and it is the shape all four
# entries wore. The debt is owed by ONE lot; a label carrying two, with nothing
# saying which half is spent, is what let the promise expire unnoticed.
#
# AND IT EXPIRED ANYWAY, on the four labels that read « L09 — the data layer
# takes it ». L09 landed having reduced the largest of them by thirteen lines
# out of the three hundred and fifty-six it owed, and this arm reported nothing
# because the status it read said L09 had not run. The debt was L14's and it is paid (`9ce9b0508`); what remains is the engine's two, L13's, and
# L14 exists in the plan because of it.
OWED_LOT = re.compile(r"^(L\d\d)\b")


def declared_and_landed_lots() -> tuple[set[str], set[str]]:
    """Read the lots the plan declares, and the lots that have landed.

    TWO DOCUMENTS, and that is the point rather than an inconvenience. The
    declaration is the plan's — it is the file that says which lots exist. The
    advancement is `IMPLEMENTATION.md`'s, and only its: a status carried in
    both files is a status that goes stale in one, which is exactly how four
    grandfather entries kept promising a lot that had already run.

    BOTH SETS, and the first one is not decoration. Holding a label only
    against the landed set leaves « L99 — the data layer takes it » green for
    ever: the plan declares a finite set of lots (read from its headings, never listed here), so a lot that will
    never run is a promise nobody can call in — B-073's own defect wearing a
    different disguise.

    Returns:
        A `(declared, landed)` pair of lot codes. EITHER MAY BE EMPTY when its
        document cannot be read, and the caller treats each emptiness as its
        own violation naming its own file — never as « the plan declares
        nothing » or « no lot has landed », which are the readings that would
        make this hold pass for the one reason it must never pass for.
    """
    declared: set[str] = set()
    if PLAN.is_file():
        declared = set(LOT_HEADING.findall(PLAN.read_text(encoding="utf-8")))
    landed: set[str] = set()
    if ADVANCEMENT.is_file():
        row = LANDED_ROW.search(ADVANCEMENT.read_text(encoding="utf-8"))
        if row is not None:
            landed = set(LOT_CODE.findall(row.group(1)))
    return declared, landed
