#!/usr/bin/env python3
"""Serve the design prototype over HTTP, behind its own login screen.

`refonte.html` is a head-less fragment: it starts at `<title>` and owns no
`<html>` or `<head>`, because it is authored to be embedded by a host page.
Served raw as a top-level document it renders in quirks mode, and a phone with
no viewport meta falls back to the legacy 980px layout viewport and scales the
frame down to roughly 40 % — measured, not feared.

This server supplies exactly the wrapper the harness builds, so the page a
browser is shown here is byte-for-byte the page the harness measures. Any
divergence between the two would make the published design unable to serve as
the reference it is meant to be.

It serves one document and nothing else. The directory around the prototype
holds the extraction contract, the harness and its scratch output; none of that
belongs on a public host.

**The credential check runs here, not in the page.** The prototype carries the
real library index, the follows and the staging contents. A check written in
the page it protects is readable by everyone that page reaches, so it protects
nothing; and the page cannot be sent before the check without giving away what
the check was for. The gate is therefore built by EXTRACTING the login screen
from the prototype — markup, styles and typeface, between explicit markers —
so the screen a visitor meets is the screen the design defines, never a copy of
it that drifts.

Only a scrypt hash of the password is stored. Set `TM_DESIGN_PASSWORD_HASH` to
rotate it without touching this file:

    python3 -c "import hashlib,os,base64; s=os.urandom(16); \\
        print(base64.b64encode(s).decode()+':'+base64.b64encode( \\
        hashlib.scrypt(b'<password>', salt=s, n=16384, r=8, p=1, dklen=32)).decode())"
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import http.cookies
import http.server
import os
import secrets
import socketserver
import sys
import urllib.parse
from pathlib import Path

PROTOTYPE = Path(__file__).resolve().parent / "design" / "refonte.html"

IDENTIFIANT = os.environ.get("TM_DESIGN_USER", "izno")

# scrypt, salt included, both base64. The password itself is nowhere here, and
# nowhere in the repository.
EMPREINTE = os.environ.get(
    "TM_DESIGN_PASSWORD_HASH",
    "6AyZBOfVp7Qj5pwFOepikA==:7sVyqbzeLHD4/FA8pUfqPb7RPSe+wmesEZi7fhXm9hw=",
)

# Regenerated at every boot: a restart ends every session, which is the right
# trade for a design host and removes any need to persist secrets.
SECRET_SESSION = secrets.token_bytes(32)
NOM_COOKIE = "tm_design"

DOSSIER_ASSETS = PROTOTYPE.parent / "assets"

# Brand assets and the manifest are served WITHOUT a session: they carry no
# private data, and a `<link rel="manifest">` is fetched without credentials
# unless asked otherwise — a 401 there costs the install prompt entirely.
#
# The DESIGN set, never the app's. A name distinguishes two entries in a list;
# on a home screen what is seen first is the picture, and two identical pictures
# with different labels are still two identical pictures. The three sets are one
# family — the app's icons plain, staging's with a cyan ring, these with a
# yellow one — and they are generated by `frontend/scripts/make-design-icons.py`
# rather than drawn by hand, so the ring cannot drift between them.
ASSETS = {
    "/pwa-192.png": "image/png",
    "/pwa-512.png": "image/png",
    "/maskable-192.png": "image/png",
    "/maskable-512.png": "image/png",
    "/apple-touch-icon.png": "image/png",
    "/favicon.svg": "image/svg+xml",
}

# The file each path is answered with. The URLs keep the app's names so the
# manifest reads the same on all three hosts; only what comes back differs.
FICHIER_ASSET = {
    "/pwa-192.png": "pwa-192-design.png",
    "/pwa-512.png": "pwa-512-design.png",
    "/maskable-192.png": "maskable-192-design.png",
    "/maskable-512.png": "maskable-512-design.png",
    "/apple-touch-icon.png": "apple-touch-icon-design.png",
    "/favicon.svg": "favicon.svg",
}

# The prototype is a SEPARATE application, and it has to say so everywhere the
# system reads a name.
#
# The shipped app installs as « TorrentMate », and this one used to install as
# « TM design » — an abbreviation nobody recognises next to it, over the same
# icon. Two entries on one home screen that differ only by an abbreviation are
# two entries nobody can tell apart, and the one that gets opened is whichever
# was tapped last.
#
# `id` is declared rather than left to default: without it the identity falls
# back to `start_url`, which is « / » here and « / » there, so nothing but the
# origin separates them. Naming it removes the ambiguity instead of relying on
# a browser to resolve it.
MANIFESTE = b"""{
  "id": "/?app=torrentmate-design",
  "name": "TorrentMate Design",
  "short_name": "TorrentMate Design",
  "description": "Prototype de r\\u00e9f\\u00e9rence de l'interface TorrentMate.",
  "lang": "fr",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "orientation": "portrait",
  "background_color": "#0b0b0d",
  "theme_color": "#0b0b0d",
  "icons": [
    { "src": "/pwa-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any" },
    { "src": "/pwa-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any" },
    { "src": "/maskable-192.png", "sizes": "192x192", "type": "image/png", "purpose": "maskable" },
    { "src": "/maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" }
  ]
}
"""

# Installability asks two things of a worker: that it handle fetches, and that
# a navigation still get an answer with the network gone. An empty handler
# satisfies the first and fails the second, so the prompt never came.
#
# The answer is NETWORK-FIRST, with one cached page as the only fallback, and
# the prototype itself never cached. A caching worker would serve yesterday's
# prototype to someone judging today's design — the exact failure a design
# reference cannot afford. Being offline says so instead of lying quietly.
WORKER = b"""const CACHE = "tm-design-offline";
const HORS_LIGNE = "/hors-ligne.html";

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.add(HORS_LIGNE)));
  self.skipWaiting();
});
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));
self.addEventListener("fetch", (e) => {
  if (e.request.mode !== "navigate") return;
  e.respondWith(
    fetch(e.request).catch(() => caches.match(HORS_LIGNE))
  );
});
"""

# The one page that exists offline. It says what is true — the prototype lives
# on the server and is not available — rather than showing a stale copy of it.
HORS_LIGNE = (
    '<!doctype html><html lang="fr"><head><meta charset="utf-8">'
    '<meta name="viewport" content="width=device-width,initial-scale=1">'
    "<title>TorrentMate Design — hors ligne</title>"
    "<style>html,body{margin:0;height:100%;display:grid;place-items:center;"
    "background:#0b0b0d;color:#ededf0;font-family:system-ui,sans-serif;"
    "text-align:center;padding:24px}p{color:#9b9ba4;font-size:14px;"
    "line-height:1.5;max-width:30ch}</style></head><body><div>"
    "<h1 style=\"font-size:17px;margin:0 0 8px\">Hors ligne</h1>"
    "<p>La maquette est servie par le serveur de design. Elle n'est pas "
    "mise en cache, pour que ce que vous jugez soit toujours la version "
    "du jour.</p></div></body></html>"
).encode()

ENVELOPPE = Path(__file__).resolve().parent / "design" / "index.html"


def tete_pwa() -> str:
    """Returns the PWA head block, extracted from the envelope.

    The envelope (`design/index.html`) is the document's single source of
    truth since the host began serving the build; the login gate sits in
    front of that document and must be installable too, so it borrows the
    same block rather than restating it — a restated copy is where drift
    hides (measured twice on the login screen's styles).

    Raises:
        ValueError: When the markers are missing — the gate must fail loudly
            rather than serve a page that silently lost its installability.
        FileNotFoundError: When the envelope itself is absent.
    """
    source = ENVELOPPE.read_text()
    debut = source.find("pwa:start")
    fin = source.find("<!-- pwa:end -->")
    ouvre = source.find("-->", debut, fin)
    if debut < 0 or fin < 0 or fin < debut or ouvre < 0:
        raise ValueError("marqueurs pwa introuvables dans design/index.html")
    return source[ouvre + 3 : fin]

def _build_head() -> bytes:
    """Build the HEAD bytes with the PWA block extracted at runtime."""
    return (
        '<!doctype html><html lang="fr"><head><meta charset="utf-8">'
        '<meta name="viewport" '
        'content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">'
        "<title>TorrentMate Design</title>"
        f"{tete_pwa()}"
        "</head><body>"
    ).encode()
TAIL = b"</body></html>"

MANQUANT = (
    '<!doctype html><html lang="fr"><head><meta charset="utf-8">'
    '<meta name="viewport" content="width=device-width,initial-scale=1">'
    "<title>Prototype indisponible</title></head><body "
    'style="font:16px system-ui;max-width:34em;margin:12vh auto;padding:0 1.5em">'
    "<h1>Prototype indisponible</h1><p>Le fichier <code>refonte.html</code> est "
    "absent du checkout servi. C'est ce qui arrive quand la copie de travail est "
    "sur une branche qui ne le porte pas.</p><p>Rien n'est perdu : le prototype "
    "est en dépôt. Revenir sur la branche qui le porte le remet en ligne "
    "aussitôt.</p></body></html>"
).encode()


def extraire(source: str, marque: str) -> str:
    """Returns the text between a pair of markers.

    Args:
        source: The prototype's full text.
        marque: The marker name, without its `login:` prefix or `:start` /
            `:end` suffix.

    Returns:
        The text between the two markers.

    Raises:
        ValueError: When either marker is missing — the gate must fail loudly
            rather than serve a login screen stripped of its design.
    """
    debut = source.find(f"login:{marque}:start")
    fin = source.find(f"login:{marque}:end")
    if debut < 0 or fin < 0 or fin < debut:
        raise ValueError(f"marqueurs login:{marque} introuvables dans le prototype")
    return source[source.index("\n", debut) + 1 : source.rindex("\n", debut, fin) + 1]


# Signing in navigates to a document of several megabytes. Until its first
# frame is painted the browser still shows THIS page, so the wait belongs here:
# without it, a tap on « Se connecter » answers with nothing at all for as long
# as the load takes, which reads as a form that did not submit.
#
# The screen shown is the prototype's own startup screen, extracted like the
# rest of the gate, so the wait that follows a sign-in is the same surface the
# document then keeps showing — not a copy of it that drifts.
BASCULE_DEMARRAGE = """
<script>
document.querySelector('#loginform').addEventListener('submit', function (e) {
  if (!e.currentTarget.checkValidity()) return;
  document.querySelector('#login').hidden = true;
  document.querySelector('#splash').hidden = false;
});
</script>
"""


def page_connexion(refusee: bool) -> bytes:
    """Builds the login page out of the prototype's own login screen.

    Args:
        refusee: True to show the rejection state.

    Returns:
        A complete HTML document.
    """
    source = PROTOTYPE.read_text()
    balisage = extraire(source, "markup")
    # The screen is drawn hidden inside the shell and centred against it. Here
    # it IS the page, so it drops both.
    balisage = balisage.replace(' id="login" hidden', ' id="login"', 1)
    balisage = balisage.replace('<form class="logincard" id="loginform"',
                                '<form class="logincard" id="loginform" method="post" action="/connexion"', 1)
    if refusee:
        balisage = balisage.replace('id="loginerr" hidden', 'id="loginerr"', 1)
    # Inside the prototype the startup screen is what the document opens on;
    # here it waits for the submit that makes it true.
    balisage += extraire(source, "splash").replace(
        ' id="splash"', ' id="splash" hidden', 1
    )
    # Everything the screen INHERITS inside the prototype — the palette, the box
    # model, the typography — is taken from it rather than restated. Both were
    # retyped here once, and both times the copy rendered correctly while the
    # reference was broken: the brand colour had been renamed to `--primary` and
    # the wordmark's line height was `normal` instead of 1.35. A retyped value
    # does not merely risk drifting; it CONCEALS a defect in the reference,
    # because the copy is the only place anyone ever looks.
    styles = (extraire(source, "font") + extraire(source, "palette")
              + extraire(source, "socle") + extraire(source, "style")
              + extraire(source, "splashstyle"))
    socle = ""
    # After the extract, so they win: inside the prototype the screen covers a
    # phone frame; here it IS the page.
    ajustements = """
  .loginscreen { position: static; min-height: 100vh; }
  /* No positioned frame to cover here: the startup screen answers to the
     viewport instead, so it stays put whatever the page does. */
  .splash { position: fixed; }
"""
    return (
        '<!doctype html><html lang="fr"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        "<title>TorrentMate Design — connexion</title>"
        f"{tete_pwa()}"
        "<style>"
        f"{socle}{styles}{ajustements}</style></head><body>{balisage}"
        f"{BASCULE_DEMARRAGE}</body></html>"
    ).encode()


def jeton() -> str:
    """Returns the session value a cookie must carry to be accepted."""
    return hmac.new(SECRET_SESSION, b"session", hashlib.sha256).hexdigest()


def mot_de_passe_correct(propose: str) -> bool:
    """Checks a password against the stored scrypt hash.

    Args:
        propose: The submitted password.

    Returns:
        True when it matches.
    """
    try:
        sel_b64, attendu_b64 = EMPREINTE.split(":", 1)
        sel = base64.b64decode(sel_b64)
        attendu = base64.b64decode(attendu_b64)
    except (ValueError, TypeError):
        return False
    calcule = hashlib.scrypt(propose.encode(), salt=sel, n=16384, r=8, p=1, dklen=32)
    return hmac.compare_digest(calcule, attendu)


class Handler(http.server.BaseHTTPRequestHandler):
    """Serves the wrapped prototype to a session, the login screen otherwise."""

    # The file is ~15 MB and changes only when the design does, so it is read
    # once per modification rather than once per request. mtime_ns, not mtime:
    # a second-resolution stamp misses two edits within the same second, which
    # is exactly the cadence of an editing session.
    _cache: tuple[int, bytes] | None = None

    protocol_version = "HTTP/1.1"

    def _document(self) -> bytes | None:
        """Returns the wrapped prototype, or None when the file is absent.

        Returns:
            The full HTML document as bytes, or None if `refonte.html` does not
            exist in the served checkout.
        """
        try:
            stamp = PROTOTYPE.stat().st_mtime_ns
        except FileNotFoundError:
            return None
        cached = Handler._cache
        if cached is None or cached[0] != stamp:
            Handler._cache = (stamp, _build_head() + PROTOTYPE.read_bytes() + TAIL)
        return Handler._cache[1]  # type: ignore[index]

    def _authentifie(self) -> bool:
        """Returns True when the request carries a valid session cookie."""
        brut = self.headers.get("Cookie")
        if not brut:
            return False
        biscuits = http.cookies.SimpleCookie()
        try:
            biscuits.load(brut)
        except http.cookies.CookieError:
            return False
        valeur = biscuits.get(NOM_COOKIE)
        return valeur is not None and hmac.compare_digest(valeur.value, jeton())

    def _send(
        self,
        status: int,
        body: bytes,
        entetes: list[tuple[str, str]] | None = None,
        type_mime: str = "text/html; charset=utf-8",
    ) -> None:
        """Writes one complete response, headers included.

        Args:
            status: HTTP status code.
            body: Response body; sent verbatim.
            entetes: Extra headers to add.
            type_mime: The Content-Type to declare.
        """
        self.send_response(status)
        self.send_header("Content-Type", type_mime)
        self.send_header("Content-Length", str(len(body)))
        # The design is read to be judged, and a judgement passed on a stale
        # copy is worse than no judgement. Revalidate every time — except where
        # a route says otherwise: hash-named assets change URL when they change
        # content, so they alone may claim immutability.
        if not any(n.lower() == "cache-control" for n, _ in entetes or []):
            self.send_header("Cache-Control", "no-store")
        for nom, valeur in entetes or []:
            self.send_header(nom, valeur)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 — name imposed by BaseHTTPRequestHandler
        """Answers a GET: the prototype to a session, the login screen otherwise."""
        chemin = self.path.split("?", 1)[0]
        if chemin == "/manifest.webmanifest":
            self._send(200, MANIFESTE, type_mime="application/manifest+json")
            return
        if chemin == "/sw.js":
            self._send(200, WORKER, type_mime="text/javascript")
            return
        # Outside the session, like the manifest: the worker caches this page at
        # install time, and that install happens before anyone has signed in.
        if chemin == "/hors-ligne.html":
            self._send(200, HORS_LIGNE, type_mime="text/html; charset=utf-8")
            return
        if chemin in ASSETS:
            fichier = DOSSIER_ASSETS / FICHIER_ASSET[chemin]
            if not fichier.is_file():
                self._send(404, b"")
                return
            self._send(200, fichier.read_bytes(), type_mime=ASSETS[chemin])
            return
        if chemin.startswith("/assets/"):
            # The library's real artwork: session-gated, unlike the brand set.
            if not self._authentifie():
                self._send(401, b"")
                return
            # self.path arrives raw: BaseHTTPRequestHandler never percent-decodes
            # it, so an encoded traversal (%2e%2e%2f) reaches the filesystem as a
            # literal file name that does not exist. The resolve() + containment
            # check below is the backstop that must hold if that ever changes.
            fichier = (DOSSIER_ASSETS / chemin[len("/assets/"):]).resolve()
            types = {".webp": "image/webp", ".png": "image/png",
                     ".svg": "image/svg+xml"}
            type_mime = types.get(fichier.suffix)
            if (type_mime is None or not fichier.is_file()
                    or not fichier.is_relative_to(DOSSIER_ASSETS.resolve())):
                self._send(404, b"")
                return
            self._send(200, fichier.read_bytes(),
                       [("Cache-Control", "private, max-age=31536000, immutable")],
                       type_mime=type_mime)
            return
        if chemin == "/deconnexion":
            self._send(303, b"", [("Location", "/"),
                                  ("Set-Cookie", f"{NOM_COOKIE}=; Path=/; Max-Age=0")])
            return
        if chemin not in ("/", "/index.html"):
            # Anything else goes back to the one document, instead of dead-ending.
            #
            # A 404 here is not a smaller failure than a broken page, it IS the
            # broken page: `/connexion` accepts only POST, so a reload or a
            # back-navigation after signing in used to answer « Rien ici » — and
            # an installed PWA, whose whole scope is `/`, has no address bar to
            # get out of it with. The scope must therefore be a place one cannot
            # leave by accident.
            self._send(303, b"", [("Location", "/")])
            return
        if not self._authentifie():
            self._send(401, page_connexion(refusee="refus" in self.path))
            return
        body = self._document()
        if body is None:
            self._send(503, MANQUANT)
            return
        self._send(200, body)

    do_HEAD = do_GET

    def do_POST(self) -> None:  # noqa: N802 — name imposed by BaseHTTPRequestHandler
        """Answers the login form: a session cookie, or the rejection state."""
        if self.path.split("?", 1)[0] != "/connexion":
            self._send(303, b"", [("Location", "/")])
            return
        taille = min(int(self.headers.get("Content-Length") or 0), 4096)
        champs = urllib.parse.parse_qs(self.rfile.read(taille).decode("utf-8", "replace"))
        identifiant = (champs.get("identifiant") or [""])[0].strip()
        motdepasse = (champs.get("motdepasse") or [""])[0]
        # Both sides compared in constant time, and the username checked even
        # when it is wrong, so a wrong name and a wrong password cost the same.
        nom_ok = hmac.compare_digest(identifiant, IDENTIFIANT)
        mdp_ok = mot_de_passe_correct(motdepasse)
        if not (nom_ok and mdp_ok):
            self._send(303, b"", [("Location", "/?refus=1")])
            return
        self._send(303, b"", [
            ("Location", "/"),
            ("Set-Cookie",
             f"{NOM_COOKIE}={jeton()}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=2592000"),
        ])

    def log_message(self, fmt: str, *args: object) -> None:
        """Silences per-request logging.

        Caddy already writes one access-log line per request; a second copy in
        the PM2 log buys nothing and grows without bound.
        """


class Server(socketserver.ThreadingTCPServer):
    """Threaded so a slow client cannot hold the single document hostage."""

    daemon_threads = True
    allow_reuse_address = True


def main() -> int:
    """Runs the server until interrupted.

    Returns:
        Process exit status.
    """
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8712
    # Bound to the loopback: the reverse proxy is the only intended caller, and
    # binding wider would publish the prototype on the LAN behind the proxy's
    # back, outside whatever access control the proxy applies.
    with Server(("127.0.0.1", port), Handler) as httpd:
        print(f"prototype served on http://127.0.0.1:{port} from {PROTOTYPE}", flush=True)
        httpd.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
